interface Parameter {
  [Const] DOMString identifier();
};

interface Attribute {
  DOMString attachment();
  DOMString identifier();
  long componentCount();
  DOMString type();
  VoidPtr data();
};

interface Mesh {
  boolean isValid();
  long pointCount();
  long cornerCount();
  long faceCount();
  long constantFaceSize();
  long attributeCount();
  [Value] Attribute getAttribute(DOMString attachment, DOMString identifier);
  [Value] Attribute getAttributeByIndex(long attributeIndex);
};

interface EffectInstance {
  long setParameter(DOMString identifier, float value);
  long cook();
  [Value] Mesh getOutputMesh();
};

interface EffectDescriptor {
  [Const] DOMString identifier();
  long load();
  long unload();
  long getParameterCount();
  [Const] Parameter getParameter(long parameterIndex);
  EffectInstance instantiate();
};

interface EffectLibrary {
  void EffectLibrary();
  boolean load(DOMString pluginFilename);
  void unload();
  long getEffectCount();
  [Const] EffectDescriptor getEffectDescriptor(long effectIndex);
};
